-- 테이블 지울 때 무결성도 같이 지워주기
DROP TABLE PERSONQNA
CASCADE CONSTRAINTS;

-- 시퀀스 지우기
DROP SEQUENCE SEQ_PERSONQNA;



-- 고객 테이블
CREATE TABLE CUSTOMER(
	ID				VARCHAR2(20) PRIMARY KEY,
	PASSWORD		VARCHAR2(20) NOT NULL,
	NAME			VARCHAR2(20) NOT NULL,
	ADDRESS			VARCHAR2(50) NOT NULL,
	BIRTHDAY		VARCHAR2(8) NOT NULL,
	PHONE			VARCHAR2(11) NOT NULL,
	AUTH			NUMBER(1)	 NOT NULL,
	EMAIL			VARCHAR2(50) NOT NULL,
	GRADE			VARCHAR2(10) NOT NULL,
	BOOKING_COUNT	NUMBER(8)	 NOT NULL,
	TOTAL_PAYMENT	NUMBER(10)	 NOT NULL
)

-- 예약 테이블
CREATE TABLE BOOKING(
	SEQ				NUMBER(10)	 PRIMARY KEY,
	ID				VARCHAR2(20),
	WDATE			DATE		 NOT NULL,
	VISIT_DATE		VARCHAR2(8) NOT NULL,
	LEAVE_DATE		VARCHAR2(8) NOT NULL,
	TOTAL_PRICE 	NUMBER(10)	 NOT NULL,
	ADULT_NUMBER	NUMBER(1)	 NOT NULL,
	CHILD_NUMBER	NUMBER(1)	 NOT NULL,
	ROOM_NUMBER		VARCHAR2(20) NOT NULL
)

-- 예약 테이블 시퀀스
CREATE SEQUENCE SEQ_BOOKING
START WITH 1
INCREMENT BY 1;

-- 방정보 테이블 ROOM_NUMBER를 참조하는 예약 테이블 외래키 : ROOM_NUMBER
ALTER TABLE BOOKING
ADD CONSTRAINT FK_BOOKING_ROOM_NUMBER FOREIGN KEY(ROOM_NUMBER)
REFERENCES ROOM(ROOM_NUMBER);

-- 방정보 테이블
CREATE TABLE ROOM(
	ROOM_NUMBER		VARCHAR2(20) PRIMARY KEY,
	PRICE			NUMBER(10) NOT NULL,
	GRADE			VARCHAR2(20) NOT NULL
)

-- 공지사항 테이블
CREATE TABLE NOTICE(
	SEQ				NUMBER(10)	 PRIMARY KEY,
	ID				VARCHAR2(20) NOT NULL,
	TITLE			VARCHAR2(50) NOT NULL,
	CONTENT			VARCHAR2(4000) NOT NULL,
	WDATE			DATE		 NOT NULL,
	DEL				NUMBER(1)	 NOT NULL,
	READCOUNT		NUMBER(10)	 NOT NULL,
	FILENAME		VARCHAR2(20) NOT NULL,
	DOWNCOUNT		NUMBER(20)	 NOT NULL
)

-- 공지사항 테이블 시퀀스
CREATE SEQUENCE SEQ_NOTICE
START WITH 1
INCREMENT BY 1;

-- 고객의 소리 테이블
CREATE TABLE PERSONQNA(
	SEQ				NUMBER(10)	 PRIMARY KEY,
	ID				VARCHAR2(20),
	TITLE			VARCHAR2(50) NOT NULL,
	CONTENT			VARCHAR2(4000) NOT NULL,
	WDATE			DATE		 NOT NULL,
	ANSWER_CHECK	NUMBER(1)	 NOT NULL,
	QUESTION_TYPE	VARCHAR2(20) NOT NULL,
	COMMENTS		VARCHAR2(4000)
)

-- 고객의 소리 테이블 시퀀스
CREATE SEQUENCE SEQ_PERSONQNA
START WITH 1
INCREMENT BY 1;



SELECT * FROM CUSTOMER
SELECT * FROM BOOKING
SELECT * FROM ROOM
