/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-09-17 09:37:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/E:/springSample/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringSamples/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/E:/springSample/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringSamples/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1566519780488L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_fmt_005frequestEncoding_005f0(_jspx_page_context))
        return;
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\" type=\"text/css\" />  \r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>  \r\n");
      out.write("<script src=\"http://code.jquery.com/ui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\"/>\r\n");
      out.write("\r\n");
      out.write("<!-- cookie -->\r\n");
      out.write("<script src=\"http://lab.alexcican.com/set_cookies/cookie.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#login_wrap {\r\n");
      out.write("\tmargin:10px;\r\n");
      out.write("}\r\n");
      out.write("#login_wrap th {\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("#main_wrap { \r\n");
      out.write("\twidth:800px; \r\n");
      out.write("\tmargin-left:auto; \r\n");
      out.write("\tmargin-right:auto; padding:0px; \r\n");
      out.write("}\t\t\t\r\n");
      out.write("#content_wrap { \r\n");
      out.write("\twidth: 100%; \r\n");
      out.write("\theight: 500px; \r\n");
      out.write("\tbackground-image:url(\"image/backa.jpg\"); \r\n");
      out.write("\tbackground-repeat:no-repeat; \r\n");
      out.write("\tbackground-position:top center;  \r\n");
      out.write("}\r\n");
      out.write("\t\t\t\r\n");
      out.write(".login_title_warp {\r\n");
      out.write("\twidth:500px; \r\n");
      out.write("\tcolor:#FFFFFF; \r\n");
      out.write("\ttext-align:center; \r\n");
      out.write("\tbackground-color:#3e5fba; \r\n");
      out.write("\tborder:solid 1px #EFEFEF; \r\n");
      out.write("\tfont-weight:bold; \r\n");
      out.write("\theight:60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* table셋팅 */\r\n");
      out.write(".content_table { width:98%; border-bottom:1px solid #EFEFEF; border-right:1px solid #EFEFEF; border-collapse:collapse; margin-left:auto; margin-right:auto;  clear:both; }\r\n");
      out.write(".content_table td, .content_table th { text-align:center; border-top:1px solid #EFEFEF; border-left:1px solid #EFEFEF; padding:0.3em; }\r\n");
      out.write(".content_table th { background-color:#4D6BB3; color:#FFFFFF; line-height: 1.7em; font-weight:normal;}\r\n");
      out.write(".content_table td { padding-left:5px; text-align:left; line-height: 1.7em; }\r\n");
      out.write(".content_table td.contents { width:100%; height:400px; overflow:auto; }\r\n");
      out.write(".content_table th, .content_table td { vertical-align:middle; }\r\n");
      out.write("\r\n");
      out.write(".content_table select { height:19px; border:#CCCCCC solid 1px; vertical-align:middle; line-height: 1.8em; padding-left:0px; }\r\n");
      out.write(".content_table select option { margin-right:10px; }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"main_wrap\">\r\n");
      out.write("\t<div id=\"middle_wrap\">\r\n");
      out.write("\t\t<div id=\"content_wrap\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div style=\"width: 502px; height: 166px; margin-left: auto; margin-right: auto;\r\n");
      out.write("\t\t\t\t\t\tposition: relative; top: 100px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"login_title_warp\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-top: 15px\">\r\n");
      out.write("\t\t\t\t\t<h2>My Home Page</h2>\r\n");
      out.write("\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"login_wrap\">\r\n");
      out.write("\t\t\t\t<form action=\"loginAf.do\" name=\"frmForm\" id=\"_frmForm\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<table class=\"content_table\" style=\"width: 75%\">\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:30%\">\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:70%\">\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<th style=\"background: #eeeeee; color: #3e5fba;\">아이디</th>\r\n");
      out.write("\t\t\t\t\t\t<td>&nbsp;<input type=\"text\" id=\"_userid\" name=\"id\" data-msg=\"ID를 \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsize=\"20px\" title=\"아이디\" style=\"border: 1px solid #dddddd\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chk_save_id\">ID 저장\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"background: #eeeeee; color: #3e5fba;\">패스워드</th>\r\n");
      out.write("\t\t\t\t\t\t<td>&nbsp;<input type=\"password\" id=\"_pwd\" name=\"pwd\" data-msg=\"패스워드를 \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsize=\"20px\" title=\"패스워드\" style=\"border: 1px solid #dddddd\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" style=\"height: 50px; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#none\" id=\"_btnLogin\" title=\"로그인\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img alt=\"\" src=\"./image/login_btn.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#none\" id=\"_btnRegi\" title=\"회원가입\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img alt=\"\" src=\"./image/regi.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</span>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(\"#_btnLogin\").click(function() {\t\t\r\n");
      out.write("\tif( $(\"#_userid\").val().trim() == \"\" ){\r\n");
      out.write("\t\talert(\"id를 입력해 주십시오\");\r\n");
      out.write("\t\t$(\"#_userid\").focus();\r\n");
      out.write("\t}\r\n");
      out.write("\telse if( $(\"#_pwd\").val().trim() == \"\" ){\r\n");
      out.write("\t\talert(\"password를 입력해 주십시오\");\r\n");
      out.write("\t\t$(\"#_pwd\").focus();\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\t$(\"#_frmForm\").attr({\"action\":\"loginAf.do\", \"target\":\"_self\"}).submit();\t\t\r\n");
      out.write("\t}\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var user_id = $.cookie(\"user_id\");\r\n");
      out.write("if(user_id != null){\t// 지정한 쿠키가 있을 때\r\n");
      out.write("\t// alert(\"쿠키 있음\");\r\n");
      out.write("\t$(\"#_userid\").val( user_id );\r\n");
      out.write("\t$(\"#chk_save_id\").attr(\"checked\", \"checked\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(\"#chk_save_id\").click(function() {\t\r\n");
      out.write("\tif( $(\"#chk_save_id\").is(\":checked\") ){\t// 체크 되었을 때\r\n");
      out.write("\t\t//alert(\"체크 됨\");\r\n");
      out.write("\t\tif( $(\"#_userid\").val().trim() == \"\" ){\r\n");
      out.write("\t\t\talert(\"id를 입력해 주십시오\");\r\n");
      out.write("\t\t\t$(\"#chk_save_id\").prop(\"checked\", false);\t\t\t\r\n");
      out.write("\t\t}else{\t// 정상 기입한 경우\r\n");
      out.write("\t\t\t// 쿠키 저장\r\n");
      out.write("\t\t\t$.cookie(\"user_id\", $(\"#_userid\").val(), {expires:7, path:'/'});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t//\talert(\"체크 없어짐\");\r\n");
      out.write("\t\t$.removeCookie(\"user_id\", {path:'/'});\r\n");
      out.write("\t}\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#_btnRegi\").click(function () {\r\n");
      out.write("\tlocation.href = \"regi.do\";\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005frequestEncoding_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:requestEncoding
    org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag _jspx_th_fmt_005frequestEncoding_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag) _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag.class);
    boolean _jspx_th_fmt_005frequestEncoding_005f0_reused = false;
    try {
      _jspx_th_fmt_005frequestEncoding_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005frequestEncoding_005f0.setParent(null);
      // /WEB-INF/views/login/login.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005frequestEncoding_005f0.setValue("utf-8");
      int _jspx_eval_fmt_005frequestEncoding_005f0 = _jspx_th_fmt_005frequestEncoding_005f0.doStartTag();
      if (_jspx_th_fmt_005frequestEncoding_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005frequestEncoding_005f0);
      _jspx_th_fmt_005frequestEncoding_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005frequestEncoding_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005frequestEncoding_005f0_reused);
    }
    return false;
  }
}
